<?php
/**
 * Created by PhpStorm.
 * User: zhifang
 * Date: 2018/3/19
 * Time: 15:16
 */

namespace app\safety\model;

use think\Model;

class RiskImgModel extends Model
{
    protected $name = 'safety_risk_img';
    public function risk()
    {
       return $this->belongsTo('Risk');
    }

    /**
     * 重写删除方法
     * 删除记录同时删除文件
     */
    public function delete()
    {
        if (file_exists($this['path'])) {
            unlink($this['path']);
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}